[package]
name = "dom-simon-awesome-sauce"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tuix = { git = "https://github.com/geom3trik/tuix.git", branch = "main" }
